# Generated by Django 4.2.21 on 2025-06-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.UUIDField()),
                ('driver_token', models.CharField(max_length=80)),
                ('decision', models.CharField(max_length=10)),
            ],
        ),
    ]
