# Generated by Django 4.2.21 on 2025-06-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "asynchronous_service_communication",
            "0003_decisioninstance_decision_taken_by_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decisioninstance",
            name="decision_taken",
        ),
    ]
